# Generated by Django 2.2.4 on 2019-09-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time of the object creation', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of the object modification', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='pool name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=50, verbose_name='pool description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pools/pictures')),
                ('trips_offered', models.PositiveIntegerField(default=0)),
                ('trips_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Verified pools are also known as official communities.', verbose_name='verified pool')),
                ('is_public', models.BooleanField(default=True, help_text='Public pools are listed in the main page so everyone know about their existence.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited pools can grow up to a fixed number of members.', verbose_name='limited')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If pool is limited, this will be the limit on the number of members.')),
            ],
            options={
                'ordering': ['-trips_taken', '-trips_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
