# Generated by Django 2.2.4 on 2019-09-06 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time of the object creation', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of the object modification', verbose_name='modified at')),
                ('is_admin', models.BooleanField(default=False, help_text="Pool admins can update the pool's data and manage its members.", verbose_name='pool admin')),
                ('used_invitations', models.PositiveSmallIntegerField(default=0)),
                ('remaining_invitation', models.PositiveSmallIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Only active users are allowed to interact in the pool.', verbose_name='active status')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_memberships', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Pool')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pool',
            name='members',
            field=models.ManyToManyField(through='pools.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
