# Generated by Django 2.2.5 on 2019-09-14 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pools', '0002_auto_20190909_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time of the object creation', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of the object modification', verbose_name='modified at')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(help_text='Pool member that is providing the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='shared_invitations', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Pool')),
                ('used_by', models.ForeignKey(help_text='User that used the code to enter the pool', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
