"""Pool invitations models."""

# Django
from django.db import models

# Utilities
from grupalcar.utils.models import GrupalModel

# Managers
from grupalcar.pools.managers import InvitationManager


class Invitation(GrupalModel):
    """Pool invitation.
    A pool invitation is a random text that acts as
    a unique code that grants access to a specific pool.
    This codes are generated by users that are already
    members of the pool and have a 'remaining_invitations'
    value greater than 0.
    """

    code = models.CharField(max_length=50, unique=True)

    # Relations
    issued_by = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        help_text='Pool member that is providing the invitation',
        related_name='shared_invitations'
    )
    used_by = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        null=True,
        help_text='User that used the code to enter the pool'
    )

    pool = models.ForeignKey('pools.Pool', on_delete=models.CASCADE)

    # Stats
    used = models.BooleanField(default=False)
    used_at = models.DateTimeField(blank=True, null=True)

    # Manager
    objects = InvitationManager()

    def __str__(self):
        """Return code and pool."""
        return '#{}: {}'.format(self.pool.slug_name, self.code)